export const INITIAL_DATA = [
  { id: '1',  patient: '김철수', clinic: '서울바른치과',   orderDate: '2024-10-21', deadline: '2024-10-27', priority: 'high',   items: [{ type: '크라운',       material: 'Zirconia / SCRP / Non-Vital', teeth: ['11', '12'],       status: '작업중',  technician: '이기공' }, { type: '어버트먼트', material: 'Custom Abutment / Ti',   teeth: ['11'],             status: '요청됨',  technician: '미배정' }] },
  { id: '2',  patient: '이영희', clinic: '연세미소치과',   orderDate: '2024-10-22', deadline: '2024-10-29', priority: 'medium', items: [{ type: '크라운',       material: 'PFM / Base Metal',           teeth: ['36', '37'],       status: '작업중',  technician: '김기공' }] },
  { id: '3',  patient: '박지민', clinic: '미래플란트치과', orderDate: '2024-10-18', deadline: '2024-10-26', priority: 'urgent', items: [{ type: '인레이',       material: 'E-max / Ceramic',            teeth: ['44', '45'],       status: '수거완료', technician: '최기공' }] },
  { id: '4',  patient: '정민수', clinic: '하늘치과',       orderDate: '2024-10-23', deadline: '2024-10-31', priority: 'low',    items: [{ type: '서지컬 가이드', material: 'Surgical Resin',            teeth: ['21', '22', '23'], status: '작업중',  technician: '미배정' }] },
  { id: '5',  patient: '최윤서', clinic: '튼튼치과',       orderDate: '2024-10-20', deadline: '2024-10-28', priority: 'medium', items: [{ type: '덴처',         material: 'Full Denture / Acrylic',     teeth: ['Upper'],          status: '발송됨',  technician: '김기공' }, { type: '개인 트레이', material: 'Custom Tray Resin', teeth: ['Lower'], status: '작업중', technician: '미배정' }] },
  { id: '6',  patient: '강하늘', clinic: '미소지음치과',   orderDate: '2024-10-24', deadline: '2024-10-30', priority: 'high',   items: [{ type: '브릿지',       material: 'Zirconia / Monolithic',      teeth: ['14', '15', '16'], status: '작업중',  technician: '이기공' }] },
  { id: '7',  patient: '홍길동', clinic: '서울바른치과',   orderDate: '2024-10-25', deadline: '2024-11-02', priority: 'medium', items: [{ type: '크라운',       material: 'Zirconia / SCRP',            teeth: ['25'],             status: '요청됨',  technician: '미배정' }] },
  { id: '8',  patient: '임꺽정', clinic: '연세미소치과',   orderDate: '2024-10-19', deadline: '2024-10-27', priority: 'high',   items: [{ type: '임플란트',     material: 'Ti-Base',                    teeth: ['46'],             status: '작업중',  technician: '박기공' }] },
  { id: '9',  patient: '장희빈', clinic: '미래플란트치과', orderDate: '2024-10-26', deadline: '2024-11-04', priority: 'low',    items: [{ type: '가이드',       material: 'Resin',                      teeth: ['11', '21'],       status: '요청됨',  technician: '미배정' }] },
  { id: '10', patient: '이순신', clinic: '하늘치과',       orderDate: '2024-10-17', deadline: '2024-10-27', priority: 'urgent', items: [{ type: '크라운',       material: 'Gold',                       teeth: ['47'],             status: '작업중',  technician: '김기공' }] },
  { id: '11', patient: '유관순', clinic: '튼튼치과',       orderDate: '2024-10-22', deadline: '2024-11-01', priority: 'medium', items: [{ type: '덴처',         material: 'Partial Denture',            teeth: ['Lower'],          status: '요청됨',  technician: '미배정' }] },
  { id: '12', patient: '안중근', clinic: '미소지음치과',   orderDate: '2024-10-24', deadline: '2024-10-28', priority: 'high',   items: [{ type: '크라운',       material: 'Zirconia',                   teeth: ['12'],             status: '발송됨',  technician: '이기공' }] },
];

export const TECHNICIANS = ['김기공', '이기공', '최기공', '박기공', '미배정'];
